import { createStyles } from "@mantine/emotion";

export const useStyles = createStyles((theme, _params, helpers) => ({
  page: {
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    gap: 20,
  },
  headerBox: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    flexWrap: "wrap",
    gap: 16,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: 800,
    color: "#0f172a",
    letterSpacing: "-0.02em",
    lineHeight: 1.2,
  },
  headerSub: {
    fontSize: 14,
    color: "#64748b",
    marginTop: 4,
  },
  rainbowCard: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.03), 0 1px 4px rgba(0,0,0,0.02)",
    border: "1px solid #f1f5f9",
    position: "relative",
    overflow: "hidden",
    padding: "20px 24px",
    "&::before": {
      content: '""',
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      height: 3,
      background: "linear-gradient(90deg, #38bdf8, #34d399, #facc15, #fb923c, #f43f5e, #d946ef, #8b5cf6)",
      opacity: 0.65,
    }
  },
  filterRow: {
    display: "flex",
    alignItems: "flex-end",
    gap: 16,
    flexWrap: "wrap",
  },
  searchInput: {
    flex: 1,
    minWidth: 260,
    "& .mantine-InputWrapper-label": {
      fontSize: 13,
      fontWeight: 700,
      color: "#334155",
      marginBottom: 6,
    },
    "& .mantine-Input-input": {
      backgroundColor: "#ffffff",
      borderColor: "#e2e8f0",
      borderRadius: 10,
      height: 42,
      fontSize: 14,
      color: "#0f172a",
      "&::placeholder": {
        color: "#94a3b8",
      },
    },
  },
  roleSelect: {
    width: 200,
    [helpers.smallerThan("xs")]: {
      width: "100%",
    },
    "& .mantine-InputWrapper-label": {
      fontSize: 13,
      fontWeight: 700,
      color: "#334155",
      marginBottom: 6,
    },
    "& .mantine-Input-input": {
      backgroundColor: "#ffffff",
      borderColor: "#e2e8f0",
      borderRadius: 10,
      height: 42,
      fontSize: 14,
      color: "#0f172a",
    },
  },
  createBtn: {
    backgroundColor: "#2563eb",
    height: 42,
    borderRadius: 10,
    fontWeight: 600,
    fontSize: 14,
    paddingInline: 18,
    boxShadow: "0 2px 8px rgba(37, 99, 235, 0.25)",
    transition: "background-color 140ms ease, transform 140ms ease",
    "&:hover": {
      backgroundColor: "#1d4ed8",
      transform: "translateY(-1px)",
    },
  },
  tableCard: {
    backgroundColor: "#ffffff",
    borderRadius: 12,
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.03), 0 1px 4px rgba(0,0,0,0.02)",
    border: "1px solid #f1f5f9",
    overflow: "hidden",
    padding: "20px 24px",
  },
  tableHeader: {
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    fontSize: 11,
    fontWeight: 700,
    color: "#64748b",
  },
  userCell: {
    display: "flex",
    alignItems: "center",
    gap: 14,
  },
  userAvatar: {
    width: 40,
    height: 40,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#ffffff",
    fontWeight: 700,
    fontSize: 14,
    flexShrink: 0,
  },
  userPrimary: {
    fontSize: 14,
    fontWeight: 700,
    color: "#0f172a",
    lineHeight: 1.25,
  },
  userSecondary: {
    fontSize: 12,
    color: "#64748b",
    lineHeight: 1.25,
  },
  userId: {
    fontSize: 11,
    fontFamily: "monospace",
    color: "#94a3b8",
    lineHeight: 1.25,
  },

  dateCell: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    color: "#64748b",
  },
  noRecordCell: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    color: "#64748b",
  },
  greenDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    backgroundColor: "#22c55e",
    display: "inline-block",
  },
  actionIconBtn: {
    color: "#64748b",
    transition: "color 140ms ease, transform 140ms ease",
    "&:hover": {
      color: "#2563eb",
      backgroundColor: "#f1f5f9",
    },
  },
  deleteActionBtn: {
    width: 32,
    height: 32,
    borderRadius: "50%",
    backgroundColor: "#fee2e2",
    color: "#ef4444",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "none",
    cursor: "pointer",
    transition: "all 140ms ease",
    "&:hover": {
      backgroundColor: "#fecaca",
      transform: "scale(1.05)",
    },
  },
  tableFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "16px 20px",
    borderTop: "1px solid #f1f5f9",
    fontSize: 14,
    color: "#64748b",
    flexWrap: "wrap",
    gap: 12,
  },
  paginationBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    border: "1px solid #e2e8f0",
    backgroundColor: "#ffffff",
    color: "#64748b",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 140ms ease",
    "&:hover": {
      borderColor: "#cbd5e1",
      backgroundColor: "#f8fafc",
    },
  },
  paginationBtnActive: {
    backgroundColor: "#2563eb !important",
    color: "#ffffff !important",
    borderColor: "#2563eb !important",
    boxShadow: "0 2px 6px rgba(37, 99, 235, 0.3)",
  },
  drawerHeaderIconCircle: {
    width: 34,
    height: 34,
    borderRadius: "50%",
    backgroundColor: "#eff6ff",
    color: "#2563eb",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  detailCard: {
    minWidth: 0,
    overflow: "hidden",
    backgroundColor: theme.white,
    borderColor: "rgba(16, 59, 102, 0.10)",
  },
  detailHeroCard: {
    backgroundColor: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 14,
    padding: 20,
    boxShadow: "0 1px 3px rgba(0,0,0,0.03)",
  },
  detailAvatarLarge: {
    width: 64,
    height: 64,
    borderRadius: "50%",
    backgroundColor: "#3b82f6",
    color: "#ffffff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 22,
    fontWeight: 700,
    flexShrink: 0,
    boxShadow: "0 4px 12px rgba(59, 130, 246, 0.25)",
  },
  detailHeroName: {
    fontSize: 20,
    fontWeight: 800,
    color: "#0f172a !important",
    lineHeight: 1.25,
  },
  detailHeroEmail: {
    fontSize: 14,
    fontWeight: 400,
    color: "#64748b !important",
    lineHeight: 1.3,
  },
  detailIdBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "3px 10px",
    borderRadius: 8,
    backgroundColor: "#f1f5f9",
    color: "#64748b !important",
    fontSize: 12,
    fontFamily: "monospace",
    fontWeight: 500,
  },
  copyBtn: {
    padding: 2,
    color: "#94a3b8 !important",
    cursor: "pointer",
    transition: "color 140ms ease",
    border: "none",
    backgroundColor: "transparent",
    display: "inline-flex",
    alignItems: "center",
    "&:hover": {
      color: "#2563eb !important",
    },
  },
  statusActiveBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "4px 12px",
    borderRadius: 20,
    fontSize: 11,
    fontWeight: 700,
    backgroundColor: "#dcfce7",
    color: "#16a34a !important",
    border: "1px solid #bbf7d0",
  },
  detailInfoCard: {
    backgroundColor: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: 12,
    padding: 16,
    display: "flex",
    alignItems: "flex-start",
    gap: 14,
    boxShadow: "0 1px 2px rgba(0,0,0,0.02)",
    height: "100%",
  },
  detailIconCircle: {
    width: 38,
    height: 38,
    borderRadius: "50%",
    backgroundColor: "#eff6ff",
    color: "#2563eb",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  detailCardLabel: {
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    fontSize: 11,
    fontWeight: 700,
    color: "#94a3b8 !important",
    lineHeight: 1.2,
    marginBottom: 2,
    display: "block",
  },
  detailCardValue: {
    fontSize: 16,
    fontWeight: 700,
    color: "#0f172a !important",
    lineHeight: 1.35,
    display: "block",
    overflowWrap: "anywhere",
  },
  detailCardSub: {
    fontSize: 12,
    fontWeight: 400,
    color: "#8e9baa !important",
    marginTop: 4,
    lineHeight: 1.4,
    display: "block",
    overflowWrap: "anywhere",
  },
  infoLabel: {
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    fontSize: theme.fontSizes.xs,
    fontWeight: 700,
    color: theme.colors.neutral[5],
    overflowWrap: "anywhere",
  },
  infoValue: {
    color: theme.colors.neutral[6],
    overflowWrap: "anywhere",
    wordBreak: "break-word",
  },
}));
