import { alpha } from "@mantine/core";
import { createStyles } from "@mantine/emotion";

export const useStyles = createStyles((theme, _params, helpers) => ({
  shell: {
    minHeight: "100dvh",
    display: "flex",
    flexDirection: "row",
    background: "#f8fafc",
  },
  desktopSidebar: {
    width: 250,
    flexShrink: 0,
    backgroundColor: "#0e1628",
    color: theme.white,
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    position: "sticky",
    top: 0,
    zIndex: 90,
    boxShadow: "2px 0 12px rgba(0,0,0,0.12)",
    [helpers.smallerThan("md")]: {
      display: "none",
    },
  },
  sidebarHeader: {
    padding: "20px 20px 24px 20px",
    display: "flex",
    alignItems: "center",
    gap: 12,
  },
  sidebarLogoBox: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "#2563eb",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: theme.white,
    boxShadow: "0 4px 12px rgba(37, 99, 235, 0.35)",
  },
  sidebarBrandTitle: {
    fontSize: 16,
    fontWeight: 800,
    color: theme.white,
    lineHeight: 1.2,
    letterSpacing: "-0.01em",
  },
  sidebarBrandSub: {
    fontSize: 11,
    color: "#94a3b8",
    lineHeight: 1.2,
  },
  sidebarNav: {
    flex: 1,
    padding: "0 12px",
    display: "flex",
    flexDirection: "column",
    gap: 4,
    overflowY: "auto",
  },
  sidebarItem: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "11px 14px",
    borderRadius: 10,
    color: "#94a3b8",
    textDecoration: "none",
    fontSize: 14,
    fontWeight: 500,
    transition: "all 140ms ease",
    cursor: "pointer",
    border: "none",
    backgroundColor: "transparent",
    width: "100%",
    "&:hover": {
      backgroundColor: "rgba(255, 255, 255, 0.07)",
      color: theme.white,
    },
  },
  sidebarItemActive: {
    backgroundColor: "#1d4ed8 !important",
    color: `${theme.white} !important`,
    fontWeight: 600,
    boxShadow: "0 4px 14px rgba(29, 78, 216, 0.35)",
  },
  sidebarFooter: {
    padding: 16,
    borderTop: "1px solid rgba(255, 255, 255, 0.08)",
  },
  sidebarLogoutBtn: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 14px",
    borderRadius: 10,
    color: "#94a3b8",
    width: "100%",
    backgroundColor: "transparent",
    border: "none",
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 500,
    transition: "all 140ms ease",
    "&:hover": {
      backgroundColor: "rgba(239, 68, 68, 0.12)",
      color: "#f87171",
    },
  },
  mainArea: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    minHeight: "100dvh",
  },
  topBar: {
    position: "sticky",
    top: 0,
    zIndex: 80,
    backgroundColor: theme.white,
    borderBottom: "1px solid #e2e8f0",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.03)",
  },
  topBarInner: {
    minHeight: 64,
    display: "flex",
    alignItems: "center",
  },
  burgerMobile: {
    [helpers.largerThan("md")]: {
      display: "none",
    },
  },
  brand: {
    color: theme.colors.brand[7],
    lineHeight: 1.1,
  },
  brandSubtle: {
    color: theme.colors.neutral[5],
  },
  content: {
    flex: 1,
    paddingBlock: theme.spacing.lg,
  },
  contentInner: {
    width: "100%",
  },
  drawerBody: {
    width: "100%",
    paddingInline: 0,
    gap: theme.spacing.md,
  },
  navPanel: {
    width: "100%",
    overflow: "hidden",
    borderRadius: theme.radius.lg,
    border: `1px solid ${theme.colors.neutral[2]}`,
    backgroundColor: alpha(theme.white, 0.92),
    boxShadow: `0 20px 40px ${alpha(theme.colors.navy[9], 0.06)}`,
  },
  navGroup: {
    borderBottom: 0,
    "&:last-child": {
      borderBottom: 0,
    },
    "& $navButton": {
      borderBottom: 0,
    },
  },
  navChildren: {
    width: "100%",
    margin: 0,
    padding: 0,
    backgroundColor: alpha(theme.colors.brand[0], 0.78),
    borderTop: `1px solid ${alpha(theme.colors.brand[7], 0.12)}`,
    "& .mantine-List-itemWrapper, & .mantine-List-itemLabel": {
      display: "block",
      width: "100%",
    },
  },
  navChildItem: {
    width: "100%",
    margin: 0,
    padding: 0,
    "&::marker": {
      content: "none",
    },
  },
  navChildLink: {
    display: "block",
    width: "100%",
    boxSizing: "border-box",
    padding: "13px 15px 13px 62px",
    color: theme.colors.neutral[7],
    textDecoration: "none",
    fontWeight: 700,
    fontSize: theme.fontSizes.sm,
    borderTop: `1px solid ${alpha(theme.colors.neutral[8], 0.06)}`,
    backgroundColor: "transparent",
    transition: "background-color 140ms ease, color 140ms ease",
    "&:hover": {
      background: "linear-gradient(180deg, #103b66 0%, #0a2a4d 100%)",
      color: theme.white,
    },
    "&:focus, &:focus-visible": {
      outline: "none",
      boxShadow: "none",
    },
  },
  navChildLinkActive: {
    background: "linear-gradient(180deg, #103b66 0%, #0a2a4d 100%)",
    color: theme.white,
  },
  navButton: {
    display: "block",
    width: "100%",
    padding: "13px 15px",
    boxSizing: "border-box",
    textDecoration: "none",
    backgroundColor: theme.white,
    color: theme.colors.neutral[6],
    border: 0,
    borderBottom: `1px solid ${theme.colors.neutral[2]}`,
    outline: "none",
    cursor: "pointer",
    transition:
      "background-color 140ms ease, color 140ms ease, transform 140ms ease",
    "&:last-child": {
      borderBottom: 0,
    },
    "&:hover": {
      background: "linear-gradient(180deg, #103b66 0%, #0a2a4d 100%)",
      color: theme.white,
    },
    "&:hover $navChevron": {
      transform: "translateX(2px)",
      color: theme.white,
    },
    "&:hover $navIconWrap": {
      color: theme.white,
    },
    "&:focus, &:focus-visible": {
      outline: "none",
      boxShadow: "none",
    },
  },
  navButtonActive: {
    background: "linear-gradient(180deg, #103b66 0%, #0a2a4d 100%)",
    color: theme.white,
    "& $navItemTitle, & $navChevron": {
      color: theme.white,
    },
    "& $navIconWrap": {
      backgroundColor: alpha(theme.white, 0.14),
      color: theme.white,
    },
    "&:hover": {
      background: "linear-gradient(180deg, #103b66 0%, #0a2a4d 100%)",
      color: theme.white,
    },
  },
  navIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "inherit",
    transition: "color 140ms ease",
  },
  navItemTitle: {
    color: "inherit",
    lineHeight: 1.2,
  },
  logoutActions: {
    width: "100%",
    marginTop: "0.5rem",
  },
  logoutDangerButton: {
    minHeight: "56px",
    fontWeight: 700,
    boxShadow: theme.shadows.md,
  },
  navChevron: {
    color: theme.colors.neutral[4],
    flexShrink: 0,
    transition: "transform 140ms ease, color 140ms ease",
  },
  navChevronOpen: {
    transform: "rotate(180deg)",
  },
}));
