create table if not exists public.tutor_teacher_messages (
  id bigint generated by default as identity primary key,
  tutor_profile_id uuid not null references public.profiles (id) on delete cascade,
  student_profile_id uuid not null references public.students (profile_id) on delete cascade,
  course_id bigint not null references public.courses (id) on delete cascade,
  teacher_profile_id uuid null references public.teachers (profile_id) on delete set null,
  message text not null,
  created_at timestamptz not null default now(),
  read_at timestamptz null,
  constraint tutor_teacher_messages_message_check check (char_length(trim(message)) between 3 and 2000)
);

create index if not exists tutor_teacher_messages_teacher_profile_id_idx
  on public.tutor_teacher_messages (teacher_profile_id, created_at desc);

create index if not exists tutor_teacher_messages_tutor_profile_id_idx
  on public.tutor_teacher_messages (tutor_profile_id, created_at desc);

create index if not exists tutor_teacher_messages_student_course_idx
  on public.tutor_teacher_messages (student_profile_id, course_id, created_at desc);


alter table public.tutor_teacher_messages
  add column if not exists read_at timestamptz null;
